Fix TypeError in test_good_comprehension_checks
The following expression from test_good_comprehension_checks will fail
to execute, because the list element from the range function has the
type int and int has no len method:

```
>>> [data for data in range(100) if len(data)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
TypeError: object of type 'int' has no len()
```

Just remove these expressions from the test case.